#!/bin/sh
node << ‘JSEOF’
var h=require(“http”),s=require(“https”),u=require(“url”);
var A=process.env.ANTHROPIC_API_KEY||””,G=process.env.GOOGLE_MAPS_API_KEY||””,N=process.env.NOOKAL_API_KEY||””,P=process.env.PORT||8080;
function cors(r){r.setHeader(“Access-Control-Allow-Origin”,”*”);r.setHeader(“Access-Control-Allow-Methods”,“GET,POST,OPTIONS”);r.setHeader(“Access-Control-Allow-Headers”,“Content-Type”);}
function rb(r){return new Promise(function(res,rej){var c=[];r.on(“data”,function(x){c.push(x);});r.on(“end”,function(){try{res(JSON.parse(Buffer.concat(c).toString()));}catch(e){res({});}});r.on(“error”,rej);});}
function fr(m,ho,p,hd,b){return new Promise(function(res,rej){var d=b?JSON.stringify(b):””;var o={hostname:ho,path:p,method:m,headers:hd||{}};if(d){o.headers[“Content-Type”]=“application/json”;o.headers[“Content-Length”]=Buffer.byteLength(d);}var r=s.request(o,function(rs){var c=[];rs.on(“data”,function(x){c.push(x);});rs.on(“end”,function(){try{res({status:rs.statusCode,body:JSON.parse(Buffer.concat(c).toString())});}catch(e){res({status:rs.statusCode,body:{}});}});});r.on(“error”,rej);if(d)r.write(d);r.end();});}
function drive(addr,base){return fr(“GET”,“maps.googleapis.com”,”/maps/api/distancematrix/json?origins=”+encodeURIComponent(addr+”, VIC, Australia”)+”&destinations=”+encodeURIComponent(base+”, Australia”)+”&mode=driving&key=”+G,{},null).then(function(r){try{var e=r.body.rows[0].elements[0];if(e.status===“OK”)return{duration:e.duration.text,distance:e.distance.text};}catch(e){}return null;}).catch(function(){return null;});}
function nookal(){var t=new Date(),f=t.toISOString().split(“T”)[0],t2=new Date(t.getTime()+30*86400000),to=t2.toISOString().split(“T”)[0];return fr(“GET”,“app.nookal.com”,”/api/v1/appointments?from=”+f+”&to=”+to,{“X-API-Key”:N},null).then(function(r){return r.body;}).catch(function(e){return{error:e.message};});}
function ai(bk,di,dt){var pr=“You are a scheduling assistant for Specialised Driver Training SDT Melbourne. All clients in Victoria Australia.\n\nDRIVE TIMES:\n”+JSON.stringify(dt)+”\n\nNOOKAL DIARY:\n”+JSON.stringify(di)+”\n\nBOOKING:\nClient: “+bk.clientName+”\nAddress: “+bk.clientAddress+”, VIC\nService: “+bk.serviceType+”\nFunding: “+(bk.funding||””)+”\nAvailability: “+(bk.availability||””)+”\nMods: “+(bk.modifications||””)+”\nNotes: “+(bk.notes||””)+”\n\nRULES:\n1. MODS FIRST disqualify if instructor lacks mod\n2. ZONE match instructor area to suburb\n3. ROUTING use drive times no dead runs\n4. Sherri NO adaptive mods\n5. Jason ONLY left foot accelerator and spinner knob\n6. Christians Tuesdays often Community OT Brunswick\n\nRespond with:\n1. RECOMMENDED INSTRUCTOR and justification\n2. GEOGRAPHIC ROUTING with drive times\n3. SUGGESTED TIME SLOT\n4. BACKUP OPTIONS\n5. FLAGS\n6. NOOKAL BOOKING NOTE”;return fr(“POST”,“api.anthropic.com”,”/v1/messages”,{“x-api-key”:A,“anthropic-version”:“2023-06-01”},{model:“claude-sonnet-4-20250514”,max_tokens:1500,messages:[{role:“user”,content:pr}]}).then(function(r){if(r.status!==200)throw new Error(“Anthropic “+r.status);var t=””;(r.body.content||[]).forEach(function(x){if(x.type===“text”)t+=x.text;});return t||“No response.”;});}
var sv=h.createServer(function(rq,rs){cors(rs);if(rq.method===“OPTIONS”){rs.writeHead(204);rs.end();return;}var pg=u.parse(rq.url,true);if(pg.pathname===”/health”){rs.writeHead(200,{“Content-Type”:“application/json”});rs.end(JSON.stringify({status:“ok”,message:“SDT running”}));return;}if(pg.pathname===”/analyse”&&rq.method===“POST”){rb(rq).then(function(bk){var bases={Christian:“Montmorency VIC”,Gabriel:“Croydon North VIC”,Greg:“Kilsyth VIC”,Jason:“Wandin North VIC”,Marc:“Werribee VIC”,Sherri:“Wandin North VIC”,Yves:“Rye VIC”};var dt={};return Promise.all(Object.keys(bases).map(function(n){return drive(bk.clientAddress,bases[n]).then(function(d){if(d)dt[n]=d;});})).then(function(){return nookal();}).then(function(di){return ai(bk,di,dt);}).then(function(rec){rs.writeHead(200,{“Content-Type”:“application/json”});rs.end(JSON.stringify({success:true,recommendation:rec,driveTimes:dt}));});}).catch(function(e){rs.writeHead(500,{“Content-Type”:“application/json”});rs.end(JSON.stringify({success:false,error:e.message}));});return;}rs.writeHead(404,{“Content-Type”:“application/json”});rs.end(JSON.stringify({error:“not found”}));});
sv.listen(P,function(){console.log(“SDT running on port “+P);});
JSEOF
